/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Moon (https://sketchfab.com/Moon_solstice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stargazing-through-the-attic-window-6b3e2a011f024ac6a6b123ed33d0ec28
Title: Stargazing through the attic window ☆
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Astronaut(props) {
  const { nodes, materials } = useGLTF('/stargazing_through_the_attic_window.glb')
  const group = useRef()

    useFrame((state) => {
    group.current.rotation.y = state.mouse.x * 0.2
    // group.current.rotation.x = -state.mouse.y * 0.2

    group.current.position.y =
        Math.sin(state.clock.elapsedTime) * 0.1
    })

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.01}>
        <group scale={50}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.face_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hair_strands_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.shirt_bands_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hair_big_chunk_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.hair_small_chunk_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.transparent_shirt_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1_lambert1_0.geometry}
            material={materials.lambert1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.necklace_lambert1_0.geometry}
            material={materials.lambert1}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlane2_eyelashes_0.geometry}
          material={materials.eyelashes}
          position={[0.182, -2.558, -1.005]}
          rotation={[-0.076, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlane3_eyelashes_0.geometry}
          material={materials.eyelashes}
          position={[-0.004, -0.763, 0.179]}
          rotation={[-0.013, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere1_lambert1_0.geometry}
          material={materials.lambert1}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.background_background1_0.geometry}
          material={materials.background1}
          position={[-38.828, -18.308, -100.009]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[493.874, 824.068, 246.544]}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MASH1_ReproMesh_particle_0.geometry}
          material={materials.particle}
          scale={0.971}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/stargazing_through_the_attic_window.glb')


